### ISSUE TITLE
1.14 port

### ISSUE THREAD

**Issue by lofcz** [Razzokk/Colored-Lights#13]
Hi, are you planning on porting this to newer versions of Minecraft? Would be amazing! Thanks for your work.

**Comment by Razzokk** [comment]
Thank you, yeah I'm planning on updating it to 1.14. But before I wanna get some more features done and I am waiting for a stable Forge 1.14 release.

**Comment by lofcz** [comment]
I've actually started the work on porting Albedo to 1.14 first off (since you rely on that) once I have it sorted out (no hardstucks so far) I'll ping you since without your core dependency you can't do much, right. Thanks for a fast answer!

**Comment by Razzokk** [comment]
Colored Lights does not depend on Albedo. Albedo just enables the colored light for the mod. I made it so you can use Colored Lights without Albedo but instead of giving of colored light its just normal minecraft light. But anyways an update for Albedo would be nice.

**Comment by theoparis** [comment]
Any updates on this for 1.16? I might have to do it myself if no one else has plans for this :/

**Comment by Razzokk** [comment]
Bad news, I decided to discontinue this mod in its current state. This is due to the way minecraft lighting works and how colored lighting interacts with other mods (bad). So I decided to stop this and basically turn it into a similar mod (development will be started soon) that has everything the mod currently has + builds on a similar idea. All of this without colored lighting ofc. If there will be a mod out there that can make colored lighting I maybe make an addon for the new mod so that it can utilize that colored lighting API.

**Comment by theoparis** [comment]
Ok :(
I know Albedo has a 1.13 version that was WIP so I was thinking I could update it. I just need colored lighting for my other mod that has a alarm, so I can make it flash red.

**Comment by Razzokk** [comment]
But then why do you need this mod in the first place?

**Comment by theoparis** [comment]
I guess I was just going off of this reply:
> I've actually started the work on porting Albedo to 1.14 first off (since you rely on that) once I have it sorted out (no hardstucks so far) I'll ping you since without your core dependency you can't do much, right. Thanks for a fast answer!

I don't need this mod lol, I guess I should make an issue on Albedo's page instead.
